version: '3'
services:
  postgresdb:
    image: 'postgres:14'
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./database:/var/lib/postgresql/database
      - ./ddl:/ddl
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - '4000:4000'
    depends_on:
      - 'postgresdb'
    environment:
      - NODE_ENV
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PORT
      - POSTGRES_HOST