version: '3'
services:
  postgresdb:
    image: 'postgres:14'
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/app
      - ./test:/test
    depends_on:
      - 'postgresdb'
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PORT
      - POSTGRES_HOST